apiVersion: apps/v1
kind: Deployment
metadata:
  name: opnsense-sftp
  namespace: opnsense-sftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opnsense-sftp
  template:
    metadata:
      labels:
        app: opnsense-sftp
    spec:
      containers:
        - name: opnsense-sftp
          image: ghcr.io/jdb-net/opnsense-sftp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: "opnsense-web"
            - containerPort: 2222
              name: "opnsense-sftp"
          env:
            - name: DB_HOST
              value: "10.10.25.4"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "opnsense-sftp"
            - name: DB_USER
              value: "opnsense-sftp"
            - name: DB_PASSWORD
              value: "n1RNwIJ9RvMiWsIE2T4H"
            - name: SECRET_KEY
              value: "hSnbupjp3T0UACP5xmLtO6TadizEBc"
            - name: ADMIN_PASSWORD
              value: "CVk7QKIB3MjZ8mt6MxES"
            - name: SFTP_PUBLIC_HOST
              value: "10.10.25.8"
            - name: SFTP_PUBLIC_PORT
              value: "30222"
          volumeMounts:
            - name: keys-volume
              mountPath: /app/keys
            - name: backups-volume
              mountPath: /app/backups
      volumes:
        - name: keys-volume
          nfs:
            server: 10.10.25.2
            path: /srv/k3s/opnsense/keys
        - name: backups-volume
          nfs:
            server: 10.10.25.2
            path: /srv/k3s/opnsense/backups
---
apiVersion: v1
kind: Service
metadata:
  name: opnsense-web-ingress-service
  namespace: opnsense-sftp
spec:
  selector:
    app: opnsense-sftp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: opnsense-sftp-service
  namespace: opnsense-sftp
spec:
  type: NodePort
  selector:
    app: opnsense-sftp
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
      nodePort: 30222
      name: sftp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opnsense-sftp-ingress
  namespace: opnsense-sftp
spec:
  rules:
  - host: opnsense-sftp.jdb143.uk
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: opnsense-web-ingress-service
            port:
              number: 80
---